services:
  - type: web
    name: django-app          
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate && gunicorn ecom.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ecom.settings  
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: CLOUDINARY_URL
        sync: false   

databases:
  - name: django-db
    plan: free
