# Generated by Django 5.2.4 on 2025-08-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_sigin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
