# Generated by Django 5.2.4 on 2025-08-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('offer', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=10)),
                ('size_1', models.CharField(max_length=20, null=True)),
                ('size_2', models.CharField(max_length=20, null=True)),
                ('size_3', models.CharField(max_length=20, null=True)),
                ('size_4', models.CharField(max_length=20, null=True)),
                ('size_5', models.CharField(max_length=20, null=True)),
                ('size_6', models.CharField(max_length=20, null=True)),
                ('size_7', models.CharField(max_length=20, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('material', models.CharField(max_length=100, null=True)),
                ('Heel_type', models.CharField(max_length=100, null=True)),
                ('Water_resistance_level', models.CharField(max_length=100, null=True)),
                ('Style', models.CharField(max_length=100, null=True)),
                ('Outer_material', models.CharField(max_length=100, null=True)),
                ('Country_of_Origin', models.CharField(max_length=100, null=True)),
                ('inf1', models.CharField(max_length=200, null=True)),
                ('inf2', models.CharField(max_length=200, null=True)),
                ('inf3', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
