# Generated by Django 5.2.4 on 2025-08-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('img', models.ImageField(upload_to='images/')),
                ('img1', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
