# Generated by Django 5.2.4 on 2025-08-15 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men_sandles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='mat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('Heel_type', models.CharField(max_length=100)),
                ('Water_resistance_level', models.CharField(max_length=100)),
                ('Style', models.CharField(max_length=100)),
                ('Outer_material', models.CharField(max_length=100)),
                ('Country_of_Origin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mshoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('offer', models.CharField(max_length=100)),
                ('brand_no', models.IntegerField()),
                ('inf1', models.CharField(max_length=200)),
                ('inf2', models.CharField(max_length=200)),
                ('inf3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='mshoes_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='imgs',
        ),
        migrations.AddField(
            model_name='mshoes',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='men_sandles.mshoes_brand'),
        ),
    ]
