# Generated by Django 5.2.4 on 2025-08-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('men_sandles', '0002_img_mat_mshoes_mshoes_brand_delete_imgs_mshoes_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='img',
            new_name='image',
        ),
    ]
