# Generated by Django 5.2.4 on 2025-08-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('men_sandles', '0003_rename_img_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
        migrations.DeleteModel(
            name='mat',
        ),
        migrations.DeleteModel(
            name='mshoes',
        ),
        migrations.DeleteModel(
            name='mshoes_brand',
        ),
    ]
